app = "grove-jbonino"
primary_region = "iad"

[build]
  [build.args]
    VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51QFzwfA3yvIY7s1WJ3kRpTHJjI8FWql4I8SmZd2MWBPP4d2nBUaWTeSLySuCUdlpjSniEU3IV7RKnaK552KqcG1T00millre6Q"

[env]
  GROVE_API_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  path = "/health"
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
